---

- name: install python3
  ansible.builtin.apt:
    name: 
      - python3
      - python3-pip
      - python3-dev
      - libpq-dev
    state: present

- name: Install setuptools
  pip:
    name: setuptools
    extra_args: --upgrade

- name: upgrade pip command
  pip:
    name: pip
    extra_args: --upgrade


- name: install pip dependencies
  pip:
    name:  pymongo
    executable: pip3


- name: Install gnupg library
  ansible.builtin.apt:
    name: gnupg
    force_apt_get: yes

- name: Add an Apt signing key
  ansible.builtin.apt_key:
    url: https://www.mongodb.org/static/pgp/server-5.0.asc
    state: present

- name: Create List file for MongoDB
  shell: >
   echo "deb [ arch=amd64,arm64 ] https://repo.mongodb.org/apt/ubuntu focal/mongodb-org/5.0 multiverse" | sudo tee /etc/apt/sources.list.d/mongodb-org-5.0.list
  args:
   chdir: "$HOME"
   creates: $HOME/filemongodb

- name: Install MongoDB Packages (Specific version)
  ansible.builtin.apt:
    name: "{{ item }}"
    update_cache: true
    force_apt_get: yes
    state: present
  loop:
      - "mongodb-org=5.0.9"
      - "mongodb-org-server=5.0.9"
      - "mongodb-org-shell=5.0.9"
      - "mongodb-org-mongos=5.0.9"
      - "mongodb-org-tools=5.0.9"  

- name: Enable service mongod
  ansible.builtin.service:
    name: mongod
    enabled: yes
    state: started


- name: rename the default configurarion file
  ansible.builtin.copy:
    src: /etc/mongod.conf 
    dest: /etc/mongod.conf-original
    mode: '0755'
    remote_src: yes

- name: create new mongod conf file
  ansible.builtin.file: 
    path: /etc/mongod.conf 
    state: touch
    
- name: configure mongod config file
  ansible.builtin.template:
    src: ./templates/mongod.conf.j2
    dest: /etc/mongod.conf 
  notify: Restart MongoDB

- name: Ensure replicaset rs0 exists
  community.mongodb.mongodb_replicaset:
    login_host: localhost
    login_port: 27017
    login_database: test
    replica_set: rs0
   