---
- name: download awe mongodb seed data
  ansible.builtin.get_url:
    url: https://refinitiv-1.s3.us-west-2.amazonaws.com/awe_db_data.tar.gz
    dest: $HOME

- name: Unarchive the compressed folder
  ansible.builtin.unarchive:
    src: awe_db_data.tar.gz
    dest: $HOME
    remote_src: yes


- name: Change ownership of folder
  ansible.builtin.file:
    path: $HOME/awe_db_data
    owner: ubuntu
    group: ubuntu
    recurse: yes


- name: Copy mongodb import script
  ansible.builtin.template:
    src: "./templates/mongodb-script.sh.j2"
    dest: "$HOME/mongodb-script.sh"
    owner: ubuntu
    group: ubuntu
    mode: '0755'


- name: Run mongodb import script
  command: ./mongodb-script.sh
  # args:
  #  chdir: "$HOME"
  #  creates: $HOME/scriptdb