---
- name: Update ubuntu
  ansible.builtin.apt:
   update_cache: yes
   force_apt_get: yes


- name: download jenkins, kubernetes & terraform keys
  apt_key: 
   url: "{{ item }}"
   state: present
  loop:
    - https://pkg.jenkins.io/debian/jenkins.io.key
    - https://packages.cloud.google.com/apt/doc/apt-key.gpg
    - https://apt.releases.hashicorp.com/gpg

- name: add jenkins, kubernetes & terraform apt repositories
  apt_repository: 
   repo: "{{ item }}"
   state: present
  loop:
    - "deb https://pkg.jenkins.io/debian binary/"
    - "deb https://apt.kubernetes.io/ kubernetes-xenial main"
    - "deb https://apt.releases.hashicorp.com/ focal  main"
  
- name: install the following packages using apt_get
  ansible.builtin.apt: 
   name: "{{ item }}"
   state: present
   update_cache: yes
   force_apt_get: yes
  loop:
    - jenkins
    - curl
    - ca-certificates
    - apt-transport-https
    - kubectl

- name: install the following packages using apt
  ansible.builtin.apt:
   name: "{{ item }}"
   state: present
   update_cache: yes
  loop: 
    - fontconfig
    - openjdk-11-jre
    - unzip
    - docker.io
    - docker-compose
    - terraform=1.0.2
    # - nodejs
    # - npm

# Anchore Engine for image scanning
- name: get anchore engine
  remote_user: ubuntu
  ansible.builtin.get_url:
    url:  https://engine.anchore.io/docs/quickstart/docker-compose.yaml
    dest: ./local-exec/docker-compose.yaml
    # owner: ubuntu
    # group: ubuntu
    mode: 0755

