---
- name: Update ubuntu
  ansible.builtin.apt:
   update_cache: yes
   force_apt_get: yes


# Install and Configure these softwares on CI server for Containerization in Pipeline
- name: install the following packages
  ansible.builtin.apt:
   name: "{{ item }}"
   state: present
   update_cache: yes
  loop: 
    - fontconfig
    - openjdk-11-jre
    - unzip
    - docker.io
    - docker-compose
    # - nodejs
    # - npm

- name: download jenkins & kubernetes keys
  apt_key: 
   url: "{{ item }}"
   state: present
  loop:
    - https://pkg.jenkins.io/debian/jenkins.io.key
    - https://packages.cloud.google.com/apt/doc/apt-key.gpg

- name: add jenkins & kubernetes apt repostiories
  apt_repository: 
   repo: "{{ item }}"
   state: present
  loop:
    - "deb https://pkg.jenkins.io/debian binary/"
    - "deb https://apt.kubernetes.io/ kubernetes-xenial main"
  
- name: install the tools
  ansible.builtin.apt: 
   name: "{{ item }}"
   state: present
   update_cache: yes
   force_apt_get: yes
  loop:
    - jenkins
    - curl
    - ca-certificates
    - apt-transport-https
    - kubectl

- name: start and enable jenkins
  ansible.builtin.service:
   name: jenkins
   state: started
   enabled: true
   daemon_reload: yes
  notify: Restart jenkins server
