---
- name: Update ubuntu
  ansible.builtin.apt:
   update_cache: yes
   force_apt_get: yes


- name: download jenkins, kubernetes, terraform & nodejs keys
  apt_key: 
   url: "{{ item }}"
   state: present
  loop:
    - https://pkg.jenkins.io/debian/jenkins.io.key
    - https://packages.cloud.google.com/apt/doc/apt-key.gpg
    - https://apt.releases.hashicorp.com/gpg
    - https://deb.nodesource.com/gpgkey/nodesource.gpg.key

- name: add jenkins, kubernetes, terraform & nodejs apt repositories
  apt_repository: 
   repo: "{{ item }}"
   state: present
  loop:
    - "deb https://pkg.jenkins.io/debian binary/"
    - "deb https://apt.kubernetes.io/ kubernetes-xenial main"
    - "deb https://apt.releases.hashicorp.com/ focal  main"
    - "deb https://deb.nodesource.com/node_16.x focal main"
  
- name: install the following packages using apt_get
  ansible.builtin.apt: 
   name: "{{ item }}"
   state: present
   update_cache: yes
   force_apt_get: yes
  loop:
    - jenkins
    - curl
    - ca-certificates
    - apt-transport-https
    - kubectl
    - nodejs


- name: install the following packages using apt
  ansible.builtin.apt:
   name: "{{ item }}"
   state: present
   update_cache: yes
  loop: 
    - fontconfig
    - openjdk-11-jre
    - unzip
    - docker.io
    - docker-compose
    - terraform=1.0.2


# Anchore Engine for image scanning
# - name: get anchore engine
#   ansible.builtin.get_url:
#     url:  https://engine.anchore.io/docs/quickstart/docker-compose.yaml
#     dest: ./local-exec/docker-compose.yaml
#     owner: ubuntu
#     group: ubuntu
#     mode: 0755

# Donwload eksctl and grype
- name: Download eksctl & grype(for scanning)
  get_url:
    url: "{{ item.url }}"
    dest: "{{ item.dest }}"
    timeout: 600
  loop:
    - {url: "https://github.com/weaveworks/eksctl/releases/latest/download/eksctl_linux_amd64.tar.gz", dest: "/tmp/eksctl_linux_amd64.tar.gz"}
    - {url: " https://raw.githubusercontent.com/anchore/grype/main/install.sh", dest: "/tmp/install.sh"}
    
- name: Unarchive eksctl binary file
  unarchive:
   src: /tmp/eksctl_linux_amd64.tar.gz
   dest: /tmp


- name: Locate  file(s) to copy
  ansible.builtin.find:
    paths: /tmp/
    recurse: yes
    patterns: eksctl*,install.sh
  register: files_to_copy
    
- name: Copy found item(s)
  ansible.builtin.copy:
    src: "{{ item.path }}"
    dest: /usr/local/bin/
    owner: ubuntu
    group: ubuntu
    mode: '0755'
    remote_src: yes
  with_items: "{{ files_to_copy.files }}"

- name: Install packages based on package.json
  community.general.npm:
    path: $HOME/simple-mern-app
    state: present