--- 
- name: download awe installation package
  ansible.builtin.get_url:
    url: https://refinitiv-1.s3.us-west-2.amazonaws.com/awe.tar.gz
    dest: $HOME

- name: Unarchive etcd binary file
  ansible.builtin.unarchive:
    src: awe.tar.gz
    dest: $HOME
    remote_src: yes


- name: Change ownership of installation package
  ansible.builtin.file:
    path: $HOME/awe
    owner: ubuntu
    group: ubuntu
    recurse: yes
  

- name: edit kafka.consumer.controller.js
  shell: >
   sed -i 's|aricuat.anp|aricprod.anp|g' $HOME/awe/controllers/kafka/consumer/kafka.consumer.controller.js


- name: edit scoreParams.controller.js
  shell: >
   sed -i 's|192.168.100.50|192.168.100.38|g' $HOME/awe/controllers/scoreParams/scoreParams.controller.js


- name: edit str.report.js
  shell: >
   sed -i 's|aricuat.anp|aricprod.anp|g' $HOME/awe/routes/kafka/consumer/str.report.js


- name:  copy aric certificate authority, client certificate and key files to scoreParams folder
  ansible.builtin.template:
    src: ./templates/{{ item }}.j2
    dest: $HOME/awe/controllers/scoreParams
  loop:
    - ca.crt
    - client.crt
    - client.key 

- name: Replace mongodb address with the correct address globally in config.env file
  shell: >
    sed -i 's|192.168.100.110|<mongodb_ip_address|g' $HOME/awe/config/config.env