---
- name: Change file permissions
  ansible.builtin.file:
    path: /etc/hosts
    mode: '0666'

## add needed ip and resolve to a local DNS name
- name: add aric ip to hosts file
  shell: >
     echo "192.168.100.50 aricuat.anp" >> /etc/hosts
  register: etc_hosts_file
  failed_when: '"192.168.100.50 aricuat.anp"  in etc_hosts_file.stdout'

   
 