---
- name: Change file permissions
  ansible.builtin.file:
    path: /etc/hosts
    mode: '0666'

## add needed ip and resolve to a local DNS name
- name: add aric ip to hosts file
  shell: >
     echo "192.168.100.50 aricuat.anp" >> /etc/hosts
  register: etc_hosts_file
  changed_when: "'192.168.100.50 aricuat.anp' not in etc_hosts_file.stdout"

   
- name: Set cap_sys_chroot+ep on /foo
  capabilities:
    path: $HOME/.nvm/versions/node/v{{item}}
    capability: cap_net_bind_service=+ep
    state: present
  loop: 
    -14.17.1