---
- name: Change file permissions
  ansible.builtin.file:
    path: /etc/hosts
    mode: '0666'

## add needed ip and resolve to a local DNS name
- name: add aric ip to hosts file
  shell: >
     echo "192.168.100.50 aricuat.anp" >> /etc/hosts
  register: etc_hosts_file
  changed_when: "'192.168.100.50 aricuat.anp' not in etc_hosts_file.stdout"

 ## set net bind service
# - name: Set cap_net_bind_service on node path
#   capabilities:
#     path: $HOME/.nvm/versions/node/v14.17.1
#     capability: cap_net_bind_service+ep
#     state: present

- name: set effective lock capability on foo binary
  file:
    path: $HOME/.nvm/versions/node/v14.17.1
    capabilities: cap_net_bind_service+ep