---
- name: Change file permissions
  ansible.builtin.file:
    path: /etc/hosts
    mode: '0666'

## add needed ip and resolve to a local DNS name
- name: add aric ip to hosts file
  shell: >
     sed -i "10 a 192.168.100.50\ aricuat.anp" /etc/hosts
   
 