---
- name: Install Nginx
  ansible.builtin.apt:
    name: nginx
    state: latest
    update_cache: yes
 
- name: download awe installation package
  ansible.builtin.get_url:
    url: https://refinitiv-1.s3.us-west-2.amazonaws.com/awe.tar.gz
    dest: /var/www

- name: Unarchive etcd binary file
  ansible.builtin.unarchive:
    src: /var/www/awe.tar.gz
    dest: /var/www
    remote_src: yes


- name: Change ownership of /var/www/awe
  ansible.builtin.file:
    path: /var/www/awe
    owner: $USER
    group: $USER
    recurse: yes
  

- name: edit kafka.consumer.controller.js
  shell: >
   sed -i 's|aricuat.anp:9094|test.go:9094|g' /var/www/awe/controllers/kafka/consumer/kafka.consumer.controller.js

- name: edit scoreParams.controller.js
  shell: >
   sed -i 's|https://192.168.100.50:8443/events|https://192.168.100.100:8443/events|g' /var/www/awe/controllers/scoreParams/scoreParams.controller.js

- name: edit str.report.js
  shell: >
   sed -i 's|aricuat.anp:9094|test.go:9094|g' /var/www/awe/routes/kafka/consumer/str.report.js


