---
- name: Setup Node
  become_user: ubuntu
  vars:
    environment: 
      HOME: /home/ubuntu
      USER: ubuntu
  become_flags: -i # Execute config files such as .profile (Ansible uses non-interactive login shells)
  block:
    - name: Install node version manager
      ansible.builtin.shell: >
        curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.35.3/install.sh | bash
      args:
        executable: /bin/bash
        chdir: "$HOME"
        creates: "$HOME/.nvm/nvm.sh"

    - name: Setup .profile
      ansible.builtin.lineinfile:
        path: $HOME/.profile
        line: source $HOME/.nvm/nvm.sh # This will make sure Node is on the user's PATH
        create: yes

############################################################
    - name: add nvm line 1 to ~/.bashrc
      lineinfile:
       path: $HOME/.bashrc
       line: 'export NVM_DIR="$HOME/.nvm"'
    

    - name: add nvm line 2 to ~/.bashrc
      lineinfile:
       path: "$HOME/.bashrc"
       line: '[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"'

    - name: add nvm line 3 to ~/.bashrc
      lineinfile:
       path: "$HOME/.bashrc"
       line: '[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"'
######################################################
    
    - name: Install node
      ansible.builtin.shell: |
       source $HOME/.nvm/nvm.sh && nvm install {{item}}
      args:
        executable: /bin/bash
        chdir: "$HOME"
        creates: "$HOME/.nvm/versions/node/v{{item}}"
      loop:
        - 14.17.1


