---

# - name: NVM | setup-Debian | Install Required Packages
#   apt:
#     name: "{{ shared_packages | union(debian_packages) }}"
#     update_cache: yes
#   # become: true

- import_tasks: nvm.yml

# - name: Install needed dependency modules globally
#   npm:
#     name: "{{item}}"
#     global: yes
#   loop: 
#     - dotenv
#     - pm2

- name: Install needed dependency modules globally
  shell: >
    source $HOME/.nvm/nvm.sh && npm install dotenv -g
  args:
   executable: /bin/bash

    # chdir: "{{ ansible_env.HOME }}"
    # creates: "{{ ansible_env.HOME }}/.nvm/nvm.sh"