---

# - name: NVM | setup-Debian | Install Required Packages
#   apt:
#     name: "{{ shared_packages | union(debian_packages) }}"
#     update_cache: yes
#   # become: true

- include: nvm.yml

- name: Install needed dependency modules globally.
  npm:
    name: "{{item}}"
    global: yes
  loop: 
    - dotenv
    - pm2