---

# - name: NVM | setup-Debian | Install Required Packages
#   apt:
#     name: "{{ shared_packages | union(debian_packages) }}"
#     update_cache: yes
#   # become: true

- import_tasks: nvm.yml

# - name: Install needed dependency modules globally
#   npm:
#     name: "{{item}}"
#     global: yes
#   loop: 
#     - dotenv
#     - pm2

- name: Install needed dependency modules globally
  shell: >
    source $HOME/.nvm/nvm.sh && npm install dotenv -g && npm install pm2@latest -g
  args:
   executable: /bin/bash

############ Redis
- name: Set up Redis repo
  shell: >
    curl -fsSL https://packages.redis.io/gpg | sudo gpg --dearmor -o /usr/share/keyrings/redis-archive-keyring.gpg
    echo "deb [signed-by=/usr/share/keyrings/redis-archive-keyring.gpg] https://packages.redis.io/deb $(lsb_release -cs) main" | sudo tee /etc/apt/sources.list.d/redis.list
  run_once: true
  ignore_errors: false

- name: Install Redis
  ansible.builtin.apt:
    name: redis
    update_cache: true
    force_apt_get: yes
  notify:
     - Enable Redis

# - name: start and enable redis
#   ansible.builtin.service:
#    name: redis
#    state: started
#    enabled: true
#    daemon_reload: yes
#   notify: Enable Redis

##############MongoDB

- name: Install gnupg library
  ansible.builtin.apt:
    name: gnupg
    force_apt_get: yes

- name: Add an Apt signing key
  ansible.builtin.apt_key:
    url: https://www.mongodb.org/static/pgp/server-5.0.asc
    state: present

- name: Create List file for MongoDB
  shell: >
   echo "deb [ arch=amd64,arm64 ] https://repo.mongodb.org/apt/ubuntu focal/mongodb-org/5.0 multiverse" | sudo tee /etc/apt/sources.list.d/mongodb-org-5.0.list
    
    



