---

# - name: NVM | setup-Debian | Install Required Packages
#   apt:
#     name: "{{ shared_packages | union(debian_packages) }}"
#     update_cache: yes
#   # become: true

- import_tasks: nvm.yml

- name: Install needed dependency modules globally
  become: true
  npm:
    executable: /root/.nvm/versions/node/v14.17.1/bin/npm
    name: "{{item}}"
    global: yes
  loop: 
    - dotenv
    - pm2