---

# - name: NVM | setup-Debian | Install Required Packages
#   apt:
#     name: "{{ shared_packages | union(debian_packages) }}"
#     update_cache: yes
#   # become: true

- import_tasks: nvm.yml

# - name: install NPM
#   shell: >
#    npm i

- name: Install needed dependency modules globally
  become: true
  npm:
    executable:  /home/ubuntu/.nvm/nvm.sh
    name: "{{item}}"
    global: yes
  loop: 
    - dotenv
    - pm2