---
- name: Update ubuntu
  ansible.builtin.apt:
   update_cache: yes


# Install and Configure these softwares on CI server for Containerization in Pipeline
- name: install java 11 and other packages
  ansible.builtin.apt:
   name: "{{ item }}"
   state: present
   update_cache: yes
  loop: 
    - fontconfig
    - openjdk-11-jre
    - docker.io
    - nodejs
    - npm
    - docker-compose


# - name: Add java stable repository from PPA
#   ansible.builtin.apt_repository:
#     repo: 'ppa:linuxuprising/java'
#     state: present
#     update_cache: yes

# - name: install java 11 and 17 versions
#   ansible.builtin.apt:
#    name: "{{ item }}"
#    state: present
#   loop:
#     - openjdk-11-jre
#     - oracle-java17-installer


# - name: set default java and javac version
#   alternatives:
#     name: "{{ item.name }}"
#     path: "{{ item.path }}"
#   loop:
#     - { name: java, path: /usr/lib/jvm/java-11-openjdk-amd64/bin/java }
#     - { name: javac, path: /usr/lib/jvm/java-11-openjdk-amd64/bin/javac}

# - name: install java 17
#   ansible.builtin.apt: 
#    name: oracle-java17-installer
#    state: present
#    update_cache: yes
#    force_apt_get: yes

- name: install jenkins apt repository key
  apt_key: 
   url: https://pkg.jenkins.io/debian/jenkins.io.key
   state: present

- name: ensure the repository is installed
  apt_repository: 
   repo: 'deb https://pkg.jenkins.io/debian binary/'
   state: present
  
- name: install jenkins
  ansible.builtin.apt: 
   name: jenkins
   state: present
   update_cache: yes
   force_apt_get: yes

- name: start and enable jenkins
  ansible.builtin.service:
   name: jenkins
   state: started
   enabled: true
   daemon_reload: yes
  notify: Restart jenkins server

# - name: Create group "docker"
#   ansible.builtin.group:
#     name: docker
#     state: present


# - name: Add user to group 'docker'
#   ansible.builtin.user:
#     name: ubuntu
#     comment: Name of user to add to group docker
#     group: docker


# - name: Change file ownership, group and permissions
#   ansible.builtin.file:
#     path: ./.docker
#     owner: ubuntu
#     group: ubuntu
#     recurse: yes
#     mode: '0666'

# - name: Change file ownership, group and permissions
#   ansible.builtin.file:
#     path: /var/run/docker.sock
#     mode: '0666'

# - name: Start docker
#   become: true
#   ansible.builtin.systemd: 
#     name: docker
#     state: restarted
#     enabled: yes
#     daemon_reload: yes