---
- name: Update ubuntu
  ansible.builtin.apt:
   update_cache: yes

- name: Add java stable repository from PPA
  ansible.builtin.apt_repository:
    repo: 'ppa:linuxuprising/java'
    state: present
    update_cache: yes

- name: install java 11
  ansible.builtin.apt:
   name: openjdk-11-jre
   state: present

# - name: install java 11 and 17 versions
#   ansible.builtin.apt:
#    name: "{{ item }}"
#    state: present
#   loop:
#     - openjdk-11-jre
#     - oracle-java17-installer


# - name: set default java and javac version
#   alternatives:
#     name: "{{ item.name }}"
#     path: "{{ item.path }}"
#   loop:
#     - { name: java, path: /usr/lib/jvm/java-11-openjdk-amd64/bin/java }
#     - { name: javac, path: /usr/lib/jvm/java-11-openjdk-amd64/bin/javac}

# - name: install java 17
#   ansible.builtin.apt: 
#    name: oracle-java17-installer
#    state: present
#    update_cache: yes
#    force_apt_get: yes

- name: install jenkins apt repository key
  apt_key: 
   url: https://pkg.jenkins.io/debian-stable/jenkins.io.key
   state: present

- name: ensure the repository is installed
  apt_repository: 
   repo: 'deb https://pkg.jenkins.io/debian-stable binary/'
   state: present
  
- name: install jenkins
  ansible.builtin.apt: 
   name: jenkins
   state: present
   update_cache: yes
   force_apt_get: yes

- name: start and enable jenkins
  ansible.builtin.service:
   name: jenkins
   state: started
   enabled: true
   daemon_reload: yes
  notify: Restart jenkins server