---
- name: Enable Redis
  ansible.builtin.systemd:
    name: redis-server
    enabled: yes
    state: restarted

- name: Enable MongoDB
  ansible.builtin.systemd:
    name: mongod
    enabled: yes
    state: restarted

- name: Enable Nginx
  ansible.builtin.systemd:
    name: nginx
    enabled: yes
    state: restarted