---
- name: Restart jenkins server
  systemd: 
    name: jenkins
    state: restarted
    enabled: yes
    daemon_reload: yes


- name: Restart docker
  ansible.builtin.systemd: 
    name: docker
    state: restarted
    enabled: yes
    daemon_reload: yes